version: "3.8"
services:
  app:
    image: ghcr.io/primariatm/decidem:latest
    user: "${UID}:${GID}"
    restart: unless-stopped
    env_file: .env
    volumes:
      - logs:/home/decidem/app/log
      - storage:/home/decidem/app/storage
    ports:
      - "${PORT}:${PORT}"
    links:
      - redis
      - caddy

  worker:
    image: ghcr.io/primariatm/decidem:latest
    restart: unless-stopped
    env_file: .env
    volumes:
      - logs:/home/decidem/app/log
      - storage:/home/decidem/app/storage
    links:
      - redis
    command: bundle exec sidekiq -C config/sidekiq.yml

  redis:
    image: redis
    volumes:
      - redis-data:/data

  caddy:
    build:
      context: caddy
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      PROXY_ADDRESS: app:3000
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - storage:/app/storage
      - caddy-data:/data
      - caddy-config:/config

volumes:
  storage: {}
  logs: {}
  static-files: {}
  redis-data: {}
  caddy-data: {}
  caddy-config: {}
