version: '3'
services:
  app:
    image: ghcr.io/primariatm/decidem:latest
    user: "${UID}:${GID}"
    restart: always
    environment:
      - PORT=3000
      - RAILS_ENV=production
      - RAILS_LOG_TO_STDOUT=true
      - RAILS_SERVE_STATIC_FILES=false
      - REDIS_URL=redis://redis:6379/1
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_DOMAIN=${SMTP_DOMAIN}
      - SMTP_ADDRESS=${SMTP_ADDRESS}
    volumes:
      - static-files:/app/public
    ports:
      - 3000:3000
    links:
      - redis
      - caddy

  worker:
    image: ghcr.io/primariatm/decidem:latest
    environment:
      - RAILS_ENV=production
      - REDIS_URL=redis://redis:6379/1
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=redis://redis:6379
    links:
      - redis
    command: bundle exec sidekiq

  redis:
    image: redis
    volumes:
      - redis-data:/data

  caddy:
    build:
      context: caddy
      dockerfile: Dockerfile
    restart: always
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      CLOUDFLARE_API_TOKEN: ${DOMAIN_NAME}
      PROXY_ADDRESS: app:3000
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - static-files:/srv
      - caddy-data:/data
      - caddy-config:/config

volumes:
  static-files: {}
  redis-data: {}
  caddy-data: {}
  caddy-config: {}
