version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    user: "${UID}:${GID}"
    restart: always
    environment:
      - PORT=3000
      - RAILS_ENV=production
      - RAILS_LOG_TO_STDOUT=true
      - RAILS_SERVE_STATIC_FILES=false
      - REDIS_URL=redis://redis:6379/1
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - BUNDLE_PATH=/bundle/vendor
    volumes:
      - static-files:/app/public
      - bundler-cache:/bundle
    ports:
      - 3000:3000
    links:
      - redis
      - caddy

  redis:
    image: redis
    volumes:
      - redis-data:/data

  caddy:
    build:
      context: caddy
      dockerfile: Dockerfile
    restart: always
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      CLOUDFLARE_API_TOKEN: ${DOMAIN_NAME}
      PROXY_ADDRESS: app:3000
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - static-files:/srv

volumes:
  static-files: {}
  bundler-cache: {}
  redis-data: {}
