:concurrency: 5
:queues:
  - [critical, 2]
  - block_user
  - default
  - exports
  - events
  - high
  - low
  - mailers
  - metrics
  - newsletter
  - newsletters_opt_in
  - translations
  - user_report
