name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  IMAGE: ghcr.io/primariatm/decidem

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      packages: read

    steps:
    - name: Deploy to production
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        envs: IMAGE
        script: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          cd /home/decidem/app
          docker-compose pull app
          docker-compose up -d

  # build:
  #   runs-on: ubuntu-latest

  #   permissions:
  #     contents: read
  #     packages: write

  #   steps:
  #   - uses: actions/checkout@v2

  #   - name: Build the Docker image
  #     run: |
  #       docker build . \
  #         --build-arg UID=${{ secrets.UID }} \
  #         --build-arg GID=${{ secrets.GID }} \
  #         --tag ${IMAGE}:$(date "+%d%m%y_%H%M") \
  #         --tag ${IMAGE}:${{ github.sha }} \
  #         --tag ${IMAGE}:latest

  #   - name: Log in to registry
  #     run: |
  #       echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

  #   - name: Push the Docker image
  #     run: |
  #       docker push ${IMAGE} --all-tags
