name: Build and deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  IMAGE: ghcr.io/primariatm/decidem

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: |
        docker build . \
          --build-arg UID=${{ secrets.UID }} \
          --build-arg GID=${{ secrets.GID }} \
          --tag ${IMAGE}:$(date "+%d%m%y_%H%M") \
          --tag ${IMAGE}:${{ github.sha }} \
          --tag ${IMAGE}:latest

    - name: Log in to registry
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push the Docker image
      run: |
        docker push ${IMAGE} --all-tags

  deploy:
    runs-on: ubuntu-latest

    needs: build

    permissions:
      packages: read

    steps:
    - uses: actions/checkout@v2

    - name: Create Sentry Release
      uses: getsentry/action-release@v1.1.6
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      with:
        environment: production
        projects: ${{ secrets.SENTRY_BACKEND_PROJECT }} ${{ secrets.SENTRY_FRONTEND_PROJECT }}
    - name: Deploy to production
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          cd /home/decidem/app
          docker-compose pull app
          docker-compose up -d
