name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build .
          --file Dockerfile
          --tag decidem:$(date "+%d%m%y_%H%M")
          --tag decidem:latest
          --build-arg UID=$UID
          --build-arg GID=$GID
    - name: Push the Docker image
      run: |
        docker push ghcr.io/primariatm/decidem --all-tags
