name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag primariatm/decidem:$(date "+%d%m%y_%H%M") --tag primariatm/decidem:latest --build-arg UID=${{ secrets.UID }} --build-arg GID=${{ secrets.GID }}
    - name: Push the Docker image
      run: |
        docker push ghcr.io/primariatm/decidem --all-tags
